name: Creates a github release (via optional new tag) and attaches current artifacts

on:
  workflow_call:
    inputs:
      tag-to-create:
        required: false
        type: string
        description: If given, a tag to create and perform release on
        default: ""

jobs:
  github-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: tag if supposed to
        shell: bash
        run: |
          if [[ "${{ inputs.tag-to-create }}" != "" ]]; then
            git tag "${{ inputs.tag-to-create }}"
            git push --tags
          else
            echo "No tag to create.. instead will fetch tags"
            git fetch --tags origin
          fi

      - name: Get version tag
        id: get-version-tag
        shell: bash
        run: |
          echo "tag=$(git tag --points-at HEAD)" | tee -a $GITHUB_OUTPUT

          # debug code
          ls -laR
          pwd

      - name: Perform release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: artifacts/*
          tag_name: ${{ steps.get-version-tag.outputs.tag }}
