name: Update the given file using markdown-autodocs

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        description: Python version to use
      cmd-to-run:
        required: true
        type: string
        description: Command including any redirection to run to generate outputs needed for markdown-autodocs
      file-to-update:
        type: string
        description: File that we intend to update
      git-ref:
        required: false
        default: ""
        type: string
        description: The git ref to build on
      operating-system:
        required: true
        type: string
        description: Operating systems to build docs on
    outputs:
      git-ref:
        description: The git ref after any changes were made
        value: ${{ jobs.markdown-autodocs.outputs.git-ref }}

jobs:
  markdown-autodocs:
    runs-on: ${{ inputs.operating-system }}
    outputs:
      git-ref: ${{ steps.doit.outputs.git-ref }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-ref }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Configure git for pushing
        shell: bash
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - uses: actions/setup-node@v3

      - name: Markdown autodocs
        id: doit
        shell: bash
        run: |
          pip install .
          ${{ inputs.cmd-to-run }}
          npm install -g markdown-autodocs
          markdown-autodocs -c code-block -o ${{ inputs.file-to-update }}
          git add ${{ inputs.file-to-update }} || true
          git commit -m "Updating readme" || true
          git push origin ${{ github.ref_name }} || true

          echo "git-ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT