name: Generate pdoc3 Documentation

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        description: Python version to build docs on
      operating-system:
        required: true
        type: string
        description: Operating system to build docs on

jobs:
  pdoc3:
    runs-on: ${{ inputs.operating-system }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Configure git for pushing
        shell: bash
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Generate and push docs
        id: doit
        shell: bash
        run: |
          if [[ -f "setup.py" ]]; then
            PROJECT_NAME="$(python setup.py --name)"
          else
            PROJECT_NAME="$(cat pyproject.toml | grep -A 100 '\[project\]' | grep '^name *' | cut -d = -f 2 | tr -d '"' | tr -d "'" | xargs)"
          fi

          python -m pip install .
          python -m pip install pdoc3 setuptools
          python -m pdoc --html "$PROJECT_NAME" -o docs_tmp -f

          rm -rf docs
          mv "docs_tmp/$PROJECT_NAME" docs
          rm -rf docs_tmp

          git add docs/* || true
          git commit -a -m "Updating docs" || true
          git pull --rebase
          git push origin ${{ github.ref_name }} || true
