name: build/upload a pyinstaller onefile

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        description: Python version to use
      operating-system:
        required: true
        type: string
        description: Operating system to build on
      executable-name:
        required: true
        type: string
        description: Name of the executable to build
      entrypoint-file:
        required: true
        type: string
        description: Entrypoint file to use

jobs:
  pyinstaller:
    runs-on: ${{ inputs.operating-system }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Build pyinstaller onefile
        id: doit
        shell: bash
        run: |
          pip install .
          pip install pyinstaller==5.13.2
          pyinstaller --onefile -n "${{ inputs.executable-name }}" "${{ inputs.entrypoint-file }}"

      - name: Simple test executable
        id: test
        shell: bash
        run: |
          echo "Testing executable via running executable with --help"
          ./dist/${{ inputs.executable-name }} --help

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.executable-name }}
          path: "dist/${{ inputs.executable-name }}"
