name: Run Tests

on:
  workflow_call:
    inputs:
      # Remember: When we want a list we instead use a string of a JSON list.. GHA doesn't support lists for inputs.
      python-versions:
        required: true
        type: string
        description: JSON-compatible list of python versions to test against
      operating-systems:
        required: false
        type: string
        description: JSON-compatible list of operating systems to test against
        default: "['ubuntu-latest','macos-latest','windows-latest']"
      install-dev-requirements:
        required: false
        type: boolean
        description: Whether to install the 'dev' requirements in addition to its own requirements (and pytest)
        default: false # only false for compatibility since some projects won't have dev requirements
      pre-install-script:
        required: false
        type: string
        default: ""
        description: Script to run before installing dev requirements

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.operating-systems) }}
        python-version: ${{ fromJSON(inputs.python-versions) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py
      - name: Update pip
        run: python -m pip install -U pip
      - name: Pre Install Script
        if: ${{ inputs.pre-install-script }} != ''
        run: ${{ inputs.pre-install-script }}
        shell: bash
      - name: Install pytest (legacy.. consider adding dev requirements then setting install-dev-requirements to true)
        if: ${{ ! inputs.install-dev-requirements }}
        run: python -m pip install pytest
      - name: Install dev dependencies
        if: ${{ inputs.install-dev-requirements }}
        run: python -m pip install .[dev]
      - name: Install 'this' requirements
        run: python -m pip install .
      - name: Run pytest
        run: python -m pytest -vvv