name: Run Tests

on:
  workflow_call:
    inputs:
      python-versions:
        required: true
        type: string
        description: "Comma delimited list of python versions to test against"
      operating-systems:
        required: false
        type: string
        description: "Comma delimited list of operating systems to test against"
        default: "ubuntu-latest,macos-latest,windows-latest"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "${{ inputs.operating-systems }}" ]
        python-version: [ "${{ inputs.python-versions }}" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install -U pip
      - name: Install pytest
        run: python -m pip install pytest
      - name: Install 'this' requirements
        run: python -m pip install .
      - name: Run pytest
        run: python -m pytest -vvv