name: Perform a patch version bump

on:
  workflow_call:

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-python@v4

      - name: Configure git for pushing
        shell: bash
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Perform version bump
        id: doit
        shell: bash
        run: |
          pip install bump2version
          bump2version patch
          git push --follow-tags
